[profile.default]
solc = "0.8.26"
fs_permissions = [{ access = "read", path = "./permit2/out/Permit2.sol/Permit2.json"}, { access = "read", path = "./test/forge/interop.json"}]
src = "./test/forge"
via_ir = true
evm_version = "cancun"
