name: "Code Quality Checks"

on:
  workflow_call:

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-test:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 2

      - name: 📥 yarn install
        shell: bash
        working-directory: ./
        run: |
          yarn --immutable
        env:
          # CI optimizations. Overrides yarnrc.yml options (or their defaults) in the CI action.
          YARN_ENABLE_GLOBAL_CACHE: "false" # Use local cache folder to keep downloaded archives
          YARN_NM_MODE: "hardlinks-local" # Hardlinks-local reduces io / node_modules size
          HUSKY: "0" # By default do not run HUSKY install

      - name: 🔬 Lint
        run: yarn g:lint

      - name: 🏗  Build
        run: yarn g:build

      - name: 🧪 Testing
        run: yarn g:test
